"""Small PBIR report-generation primitives."""

__version__ = "0.1.0"

from .layout import Frame, Grid, HStack, Padding, VStack
from .layout_tree import (
    GridNode,
    HStackNode,
    LayoutDebugStyle,
    LayoutNode,
    VStackNode,
    VisualPlacement,
    apply_layout,
)
from .pbir import (
    BarChart,
    CartesianBinding,
    Card,
    ClusteredColumnChart,
    FieldRef,
    GeneralFormatting,
    ImageVisual,
    LineChart,
    Matrix,
    MeasureRef,
    Page,
    Position,
    Report,
    Shape,
    SlicerBinding,
    Slicer,
    SummaryBinding,
    Table,
    TabularBinding,
    TextBox,
    Visual,
    VisualBinding,
    write_report,
)

__all__ = [
    "__version__",
    "apply_layout",
    "BarChart",
    "CartesianBinding",
    "Card",
    "ClusteredColumnChart",
    "FieldRef",
    "Frame",
    "GeneralFormatting",
    "Grid",
    "GridNode",
    "HStack",
    "HStackNode",
    "ImageVisual",
    "LayoutDebugStyle",
    "LayoutNode",
    "LineChart",
    "Matrix",
    "MeasureRef",
    "Padding",
    "Page",
    "Position",
    "Report",
    "Shape",
    "SlicerBinding",
    "Slicer",
    "SummaryBinding",
    "Table",
    "TabularBinding",
    "TextBox",
    "Visual",
    "VisualPlacement",
    "VStack",
    "VStackNode",
    "VisualBinding",
    "write_report",
]
