"""Small PBIR report-generation primitives."""

__version__ = "0.1.0"

from .pbir import (
    BarChart,
    CartesianBinding,
    Card,
    ClusteredColumnChart,
    FieldRef,
    GeneralFormatting,
    ImageVisual,
    LineChart,
    Matrix,
    MeasureRef,
    Page,
    Position,
    Report,
    Shape,
    SlicerBinding,
    Slicer,
    SummaryBinding,
    Table,
    TabularBinding,
    TextBox,
    Visual,
    VisualBinding,
    write_report,
)

__all__ = [
    "__version__",
    "BarChart",
    "CartesianBinding",
    "Card",
    "ClusteredColumnChart",
    "FieldRef",
    "GeneralFormatting",
    "ImageVisual",
    "LineChart",
    "Matrix",
    "MeasureRef",
    "Page",
    "Position",
    "Report",
    "Shape",
    "SlicerBinding",
    "Slicer",
    "SummaryBinding",
    "Table",
    "TabularBinding",
    "TextBox",
    "Visual",
    "VisualBinding",
    "write_report",
]
